- name: Close Stale Issues
  uses: actions/stale@v5.2.0
  permissions:
    issues: write

name: 'Close stale issues'
on:
  workflow_dispatch:
  schedule:
    - cron: '30 1 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v5
        with:
          stale-issue-label: status
          stale-issue-message: 'This issue has not received a response in 60 days. It will auto-close in 7 days unless a response is posted.'
